version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: contenedor_tenpo
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tenpo
    ports:
      - "5433:5432"
    networks:
      - postgres_data:/var/lib/postgresql/data
  app:
    image: mi_imagen_spring
    container_name: app_spring
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tenpo
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
volumes:
  postgres_data:
